### ISSUE TITLE
Can you add command /nav <player> ?

### ISSUE THREAD

**Issue by ghost** [Raqbit/CompassNavigator#1]
Can you add navigation to the player? Command like `/nav <player>` and permission 
`compassnavigator.player`

**Comment by raqbit** [comment]
With "navigation to player", do you mean the location of that player on execute,  or would it update the location while you set it?

**Comment by ghost** [comment]
When I want to get to someone, the compass tells me where to go. It would be great if the compass updated the player's current position, but it is enough when the compass shows an old position when I wrote `/nav <player>`

**Comment by raqbit** [comment]
Added in v1.2, which you can download [here](https://www.spigotmc.org/resources/compassnavigator.15948/). 
Thanks for the suggestion!
